shortcodes/custom_teasers/shortcake.php
shortcodes/faculties/controller.php
shortcodes/faculties/shortcake.php
shortcodes/faculties/view.php
shortcodes/index.php

Et comme je suis sympa, si vous voulez faire des tests:
```[epfl_faculties title1="Faculté de l'Environnement Naturel, Architectural et Construit" subtitle1="ENAC" link1="https://www.perdu.com/" image1="173" title2="Informatique et Communications" subtitle2="IC" link2="https://www.perdu.com/" image2="151" title3="Sciences de Base" subtitle3="SB" link3="https://www.perdu.com/" image3="136" title4="Sciences et Techniques de l'Ingénieur" subtitle4="STI" link4="https://www.perdu.com/" image4="118" title5="Sciences de la Vie" subtitle5="SV" link5="https://www.perdu.com/" image5="136" title6="Collège des Humanités" subtitle6="CDH" link6="https://www.perdu.com/" image6="140" title7="Collège du Management de la Technologie" subtitle7="CDM" link7="https://www.perdu.com/" image7="142" /]```

Faculties shortcode implementation

---

shortcodes/faculties/shortcake.php
shortcodes/faculties/view.php

Lié à la demandé de @frizzymagma 
Merci de review/merge et inclure dans la prochaine release ;-)

increase faculty number to 10  fix #57

---

shortcodes/epfl_memento/templates/card-slider-footer.php

Correction d'une balise div mal fermée

div tag badly closed

---

shortcodes/epfl_news/view.php

En attendant de modifier l'api REST d'actu. Un patch qui permettra aux images de s'afficher en "grand" dans une qualité "correcte" pour le copil

fix big image for news shortcode

---

sidebar.php

ajout de la search icon avec la nouvelle url de l'outil de recherche. pour le copil

add search icon in heading for copil

---

functions.php
shortcodes/page_highlight/view.php
shortcodes/page_teaser/view.php
shortcodes/post_highlight/view.php
shortcodes/post_teaser/view.php

use custom excerpt function to enable the wanted logic wanted. Whether it's auto-generated excerpts or manually inputted
fix #45

New excerpts

---

shortcodes/epfl_news/view.php

2ème essai car j'ai pas fait tous les changements nécessaires.
En attendant de modifier l'api REST d'actu. Un patch qui permettra aux images de s'afficher en "grand" dans une qualité "correcte" pour le copil

fix big visual

---

shortcodes/epfl_memento/templates/card-img-top.php

epfl-memento : Un FIX pour la résolution des images en attendant d'améliorer l'API REST

fix resolution image

---

shortcodes/epfl_news/view.php

Corrige un bug lié au shortcode epfl-news de balise html qui fermait pas bien ...

Fix problème de balise qui ferme pas dans un template de epfl-news

---

shortcodes/epfl_links_group/controller.php
shortcodes/epfl_links_group/view.php
shortcodes/index.php

Render du shortcode [links_group](https://epfl-idevelop.github.io/elements/#/molecules/links-group).
2 templates :  
1. Links block
1. Links group

render epfl_links_group

---

shortcodes/epfl_cover/controller.php
shortcodes/epfl_cover/view.php
shortcodes/index.php

Render du shortcode [cover](https://epfl-idevelop.github.io/elements/#/molecules/cover).

Render Cover

---

index.php
page.php
sidebar.php
single.php
template-parts/breadcrumb.php

désormais les pages d'accueil auront le même comportement que toutes les autres, et réagissent au template uniquement
fix https://github.com/epfl-idevelop/wp-theme-2018/issues/82

Fix homepage behaviour

---

shortcodes/epfl_map/controller.php
shortcodes/epfl_map/view.php
shortcodes/index.php

render epfl-map

---

shortcodes/epfl_news/controller.php

Supprime le paramètre stickers dans le shortcode epfl-news

delete stickers parameter

---

shortcodes/epfl_people/view.php

Un petit fixe pour l'URL de la room de epfl-people

fix url room

---

shortcodes/epfl_cover/view.php

Affiche l'icon information seulement si le champ description es renseigné.

check if description exists

---

shortcodes/epfl_cover/view.php

- Print image from id, not form an url
- Crop to 16.9 if too big

Fix epfl_cover way to print an image

---

shortcodes/epfl_card/view.php

So we can use the richtext in shortcake without breaking the whole component

Move from a clickable card to a static card with links

---

shortcodes/epfl_people/controller.php
shortcodes/epfl_people/view.php

Linked to jahia2WP PR https://github.com/epfl-idevelop/jahia2wp/pull/687

Allow to set multiple columns on people render

---

shortcodes/epfl_publication/renderers/fields.php
shortcodes/epfl_publication/renderers/publications.php

Fix some named parameter problems, as it is not valid in PHP ( #114 )

Fix infoscience search warnings

---

shortcodes/epfl_contact/view.php

Match with https://github.com/epfl-idevelop/jahia2wp/pull/708

Remove the sanitize on the richtext render

---

shortcodes/epfl_people/view.php

Match https://github.com/epfl-idevelop/jahia2wp/pull/709

Add a way to render people in list

---

template-parts/breadcrumb.php

$item -> $crumb_item

---

shortcodes/epfl_people/view.php

* Add full tel number on card view
* Don't show empty office or position in card view

Update people render

---

shortcodes/epfl_publication/render.php

Lié à https://github.com/epfl-idevelop/jahia2wp/pull/732/

Fix wrong context for translation

---

shortcodes/epfl_quote/view.php

Pour le shortcode epfl-quote, on crop l'image en carré.

Crop quote image with square crop

---

shortcodes/page_highlight/view.php

Pour le shortcode highlight page, on utilise le thumbnail large = 1024 x 1024 pour la media query (min-width: 1140px).

shortcode 'highlight page' Improve image width

---

shortcodes/post_teaser/view.php

Correction du bug de Post teaser qui s'affichait mal si on activait le fond gris

fix post teaser

---

template-parts/language-switcher.php

It needs the latest styleguide code to work

Add multi language navigation design

---

template-parts/language-switcher.php

Corrige https://github.com/epfl-idevelop/elements/issues/368, selon https://epfl-idevelop.github.io/elements/#/atoms/nav-lang

Remove unused class for nav lang

---

functions.php
header.php
template-parts/breadcrumb.php

As we don't have anymore hidden instances, we can set the url logo and the breadcrumb home to a static value

Set epfl root url to a static value

---

shortcodes/epfl_people/utils.php
shortcodes/epfl_people/view.php

Dans people, on affiche la fonction de la personne. Le problème est que je ne tenais pas compte de l'ordre pour prendre la fonction n°1 (=ordre) de la personne.
Cette PR corrige cela et j'en ai profité pour ne prendre QUE la fonction d'ordre 1 car on utilise que celle là dans les templates.

Fix order function people problem

---

languages/fr_FR.po

Ajout de quelques traductions manquantes

Add missing translations (1ere iteration)

---

shortcodes/epfl_people/utils.php

Dans people, il y a eu un changement du champ fonction en fonction_en ou fonction_fr.
Cette PR a pour but de répercuter les changements dans le shortcode

Update fonction_fr or fonction_en after change into people app

---

shortcodes/epfl_people/utils.php

- Dans le webservice people, le tableau contenant les différents numéro de téléphones d'une personne contient des strings vides. Donc amélioration de la création du tableau des phones d'une personne.
- Certaines personnes ont qu'une seule unité mais qui n'est pas d'ordre 1. Donc fix pour récupérer la fonction pour ces personnes là.

fix phones array

---

menus/submenu.php

Visible at https://www.epfl.ch/campus/spiritual-care/fr/index-fr-html/ only for a short period of time.

Re-do #189 correctly

---

shortcodes/epfl_people/utils.php

Cette PR est liée à [https://github.com/epfl-idevelop/jahia2wp/pull/971](https://github.com/epfl-idevelop/jahia2wp/pull/971)

Use doctoral_program parameter

---

wp-theme-2018/header.php

* Set logo and header link to different homes urls
* Fix top menu on theme light

Fix theme light menus

---

wp-theme-2018/shortcodes/schools/view.php

Selon https://epfl-webvolution.atlassian.net/browse/WEBEVOL-3

Fix schools padding

---

wp-theme-2018/footer.php

Remplacement de la class "pt-5" par "py-5" sur le <div> qui englobe le footer.
https://epfl-webvolution.atlassian.net/browse/WEBEVOL-12

Add bottom padding to the footer

---

wp-theme-2018/shortcodes/epfl_contact/view.php

Voir https://epfl-webvolution.atlassian.net/browse/WEBEVOL-15

Fix missing ending div for contact shortcode (WEBEVOL-15)

---

wp-theme-2018/shortcodes/hero/view.php

https://epfl-webvolution.atlassian.net/browse/WEBEVOL-5

Wrap shortcode text with <p> tag

---

wp-theme-2018/footer_en.php
wp-theme-2018/footer_fr.php

Afin de réduire le Pageranking de sites externes à l'EPFL dans le footer, on y ajoute le rel="nofollow"

Add nofollow to footer links

---

wp-theme-2018/shortcodes/epfl_polylex_search/view.php

M. Gozel demande que :
- Le texte explicatif de chaque LEX ne doit pas être en italique 
- Les dates au format jj.mm.yyyy
- Noms des personnes au format Prénom Nom, par exemple Françoise Chardonnens et non Chardonnens Françoise

Fix polylex feedback

---

wp-theme-2018/shortcodes/epfl_polylex_search/javascript.php
wp-theme-2018/shortcodes/epfl_polylex_search/view.php

- Ordre sur les combobox
- Résout le problème du Amperstand dans le texte des combobox

Polylex improve

---

wp-theme-2018/template-parts/content-page.php

Fixe les règles d'affichage du bloc Hero.
Les règles se basent sur une REGEX qui "cherche" un shortcode ... maintenant c'est un bloc

Fix hero rules

---

wp-theme-2018/header.php
wp-theme-2018/sidebar.php

- Removed in the hamburger main entry
- Removed from the header

Remove 50 years artefacts

---

wp-theme-2018/footer_en.php
wp-theme-2018/footer_fr.php

Add plan.epfl.ch in footer

---

wp-theme-2018/footer_en.php
wp-theme-2018/footer_fr.php

Add "back to top" button markup to the WP theme

---

wp-theme-2018/inc/media-gallery.php

Linked to https://github.com/epfl-si/elements/pull/439

Update gallery drawer to match with last styleguide

---

wp-theme-2018/header.php

Needed by https://github.com/epfl-si/elements/blob/3371e14a43779114e2cdb224e9baf2b5a461ddfe/assets/icons/svg-icons.js#L15

Fix missing feather sprite link

---

wp-theme-2018/editor-styles.css

Linked to https://github.com/epfl-si/elements/pull/447

Remove unavailable Open font

---

wp-theme-2018/inc/media-gallery.php

Linked to https://github.com/epfl-si/wp-gutenberg-epfl/pull/194

Migrate gallery wrapper to wp gutenberg

---

wp-theme-2018/theme/style.min.css
wp-theme-2018/theme/style.scss

https://epfl-webvolution.atlassian.net/browse/WEBEVOL-83

Improve spacing after '.container-full' element

---

wp-theme-2018/template-parts/content-post-card.php

On blog home, add the .h3 class to post titles.
https://epfl-webvolution.atlassian.net/browse/WEBEVOL-92

Improve font size of blog posts (blog list)

---

wp-theme-2018/functions.php

See https://epfl-webvolution.atlassian.net/browse/WEBEVOL-10

Refactor titles construction

---

wp-theme-2018/editor-styles.css
wp-theme-2018/functions.php

Linked to https://github.com/epfl-si/wp-mu-plugins/pull/16

Remove hiding password settings in css, as Gutenberg reset it anyway

---

wp-theme-2018/inc/media-gallery.php

By parsing the default generated dom, we can the caption set in the block, instead the one in media  gallery

Fix custom caption gallery

---

wp-theme-2018/header.php

Fix https://github.com/epfl-si/wp-theme-2018/issues/245
See https://developer.wordpress.org/reference/classes/walker/walk/

Fix walker definition

---

wp-theme-2018/inc/media-gallery.php

Corrige certains "PHP Warning", trouvés sur des sites bien fournis comme /campus/services/website en mode debug.

Fix gallery warnings

---

wp-theme-2018/menus/custom-nav-walker.php

Testé sur un site en production avec menu complet:
avant 184kB 1.77s-1.83s
après 162kB 1.41s-1.49s

Remove useless classes in menu elements

---

wp-theme-2018/searchform.php

Should fix https://github.com/epfl-si/wp-ops/issues/400

Fix 404 search on mobile

---

wp-theme-2018/header-top-menu-fallback-de.php
wp-theme-2018/header-top-menu-fallback-en.php
wp-theme-2018/header-top-menu-fallback-fr.php
wp-theme-2018/header.php
wp-theme-2018/sidebar.php

With https://github.com/epfl-si/wp-plugin-epfl-settings/pull/1

Hide or show corona info links

---

wp-theme-2018/footer_de.php
wp-theme-2018/footer_en.php
wp-theme-2018/footer_fr.php
wp-theme-2018/header-top-menu-fallback-de.php
wp-theme-2018/header-top-menu-fallback-fr.php

- Correction de liens dans les footer en français et anglais
- Ajout de target="_blank" et de rel="noopener" pour les liens externes à l'EPFL
- Nouvelles url pour les header et footer en allemand

Révisions header + footer (FR, DE, EN)

---

wp-theme-2018/template-parts/content-page.php

https://epfl-webvolution.atlassian.net/browse/WEBEVOL-142

Reduce space between page title and content

---

wp-theme-2018/functions.php

https://epfl-webvolution.atlassian.net/browse/WEBEVOL-137

[fix] title of www must be <title>EPFL</title>

---

wp-theme-2018/header.php
wp-theme-2018/searchform.php

Revert https://github.com/epfl-si/wp-theme-2018/pull/298

remove alert to search within EPFL

---

wp-theme-2018/template-parts/breadcrumb.php

This combine the old way and the new "menu-api" way to construct the  breadcumb.

feat(menu): use the menu-api

---

wp-theme-2018/template-parts/breadcrumb.php

- Soften Polylang dependency
- Wrap calls to the Web service with functions whose name state the “why,” rather than the “how”

[fix] Stylistic and functional issues with #309

---

wp-theme-2018/inc/language.php

[fix] Get default langiage only if Polylang is not installed
