epfl-si/wp-theme-2018

shortcodes/epfl_news/view.php

Pour les templates news du style "highlighted", il faut que ces templates prennent toute la largeur.

Fix container full for 2 news templates

---

shortcodes/epfl_news/utils.php
shortcodes/epfl_news/view.php

Pour le shortcode epfl-news.
Si pour une news ayant pour slug <slug>, il existe un fichier .mp4 ayant pour nom teaser_<slug>.mp4 alors cette video sera affiché à la place du visual de la news pour les templates de homepage (id=2 et id=3)

epfl news video mp4

---

shortcodes/epfl_card/view.php
shortcodes/epfl_cover/view.php
shortcodes/epfl_links_group/view.php
shortcodes/epfl_memento/controller.php
shortcodes/epfl_memento/templates/card-img-top.php
shortcodes/epfl_memento/templates/card-info.php
shortcodes/epfl_memento/templates/card-slider-footer.php
shortcodes/epfl_memento/view.php
shortcodes/epfl_news/view.php
shortcodes/epfl_scienceqa/controller.php
shortcodes/epfl_scienceqa/view.php
shortcodes/epfl_toggle/view.php
shortcodes/epfl_video/view.php

Echappe les variables utilisées dans les templates
Utilisation de : 
- esc_url() pour les urls
- esc_attr() pour les attributs
- esc_html() pour les variables placées dans une balise html
- wp_kses_post() pour les variables placées dans une balise html qui contiennent des balises HTML à conserver (strong, etc)
Suppression de "scories" de ob_start(); ob_end_flush();

Fix escape html

---

shortcodes/epfl_video/controller.php
shortcodes/epfl_video/view.php

- supprimer les paramètres width et height du shortcode epfl-video
- cela a été fait pour le shortcode epfl-video 2010 mais pas pour celui présent dans le plugin epfl

clean width and heigt parameters

---

404.php

Remove the search engine from the 404 page, and keep it as simple as possible, until we got a new 404 from Elements

Simplify the 404 page

---

shortcodes/epfl_toggle/view.php

Jusqu'à présent, uniquement le titre d'un toggle était utilisé comme identifiant donc si on avait 2x le même titre, l'affichage ne se faisait pas correctement. Cette PR résout le problème.
Et j'ai remarqué qu'il y avait un petit bug dans l'affichage si on mettait plusieurs Toggle à la suite. Le premier, WordPress l'ajoute dans un `<p>`, ce qui fait qu'il y a une marge qui est ajoutée automatiquement à la fin... mais pour les Toggles suivants, pas de problème.

Ensure that toggle ID is unique (or seriously reduce collision risk)

---

shortcodes/epfl_links_group/view.php

Pour le shortcode epfl_links_group, on ajoute une marge afin que par exemple, lorsque l'on ajoute 2 shortcodes epfl_links_group, les 2 éléments ne soient pas "collés"

Shortcode epfl_links_group: Add margin

---

menus/custom-nav-walker.php
shortcodes/custom_teasers/shortcake.php
shortcodes/epfl_publication/renderers/publications.php
shortcodes/page_teaser/shortcake.php
shortcodes/post_teaser/shortcake.php
sidebar.php
template-parts/breadcrumb.php

1. Correction de quelques PHP notices qui me pourrissaient les log quand debug activé.
1. Gestion de l'absence de breadcrumb (cas de figure rencontré lorsque l'on créé un site WWW2018 from scratch).

Fix php notices

---

shortcodes/epfl_social_feed/twitter_view.php

Dans certains cas, l'affichage de Twitter ne se fait pas. Si ce n'est une protection de twitter lorsqu'une url est trop demandée, j'ai quelques raisons de penser que le probème provient du tracking activé de twitter. En effet, il s'avère parfois que de désactiver l'option "Don't track" dans firefox raffiche la timeline Twitter. Cette PR pourrait donc résoudre ceci.
voir https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/guides/embedded-tweet-parameter-reference.html -> dnt

Active the "don't track" option for Twitter

---

template-parts/breadcrumb.php

Because of a missing class, the breadcrumbs had a bad responsive behaviour. This changes fixes it.
good test example: https://www.epfl.ch/schools/enac/fr/education-fr/genie-civil/formation-gc/master-gc/projet-de-master-a-lepfl/en-mobilite/

fix breadcrumbs

---

functions.php
header.php

* Guarded by option 'epfl2018-root-menu-overrides-enabled'; does nothing unless option is set
* If option is set, a new menu location appears in the theme ('Top Menu Override', translatable like all the others)
* Any menu entry that has the same title as a menu entry at the root of the main menu, replaces it whenever the top navigation bar is rendered.

Ability to override root menus with personalized entries

---

header.php

Labs want to exist at EPFL → Labs → MYLAB. We don't want "Labs" to show up in the top menu.
High-level changes:
* Menu entries that have exactly one ExternalMenuItem as children (and nothing else) are omitted from the top menu
Low-level changes:
* Implement that check in the ->walk() method of our custom menu walker
* [Rely on the epfl plug-in](https://github.com/epfl-idevelop/jahia2wp/pull/906) to tell us how many ExternalMenuItem children there are to any given node

"Phantom" menu entry (for labs at the root)

---

shortcodes/epfl_news/view.php

Dans le shortcode news, on voulait que le template avec 3 news (id=2) ne soit utilisé uniquement par mediacom donc on avait mis le link "all news" en dur. Maintenant on veut que ce template puisse être utilisé par tous ...

fix all news

---

wp-theme-2018/functions.php
wp-theme-2018/shortcodes/custom_teasers/view.php
wp-theme-2018/shortcodes/epfl_card/view.php
wp-theme-2018/shortcodes/epfl_cover/view.php
wp-theme-2018/shortcodes/hero/view.php
wp-theme-2018/shortcodes/schools/view.php

Lorsque l'on upload une image, WordPress créé un certain nombre de miniatures de tailles prédéfinies. Il est possible d'ajouter de nouvelles tailles via la fonction `add_image_size`, c'est ce qui a été fait pour le thème qu l'on utilise (ex) :
> add_image_size( 'thumbnail_16_9_large', 1920, 1080, ['center', 'center'] );
Ceci a pour effet de créer une miniature de 1920x1080 pour toutes les images supérieures à cette taille qui sont uploadées sur le site. Les informations `center` sont utilisées pour "cropper" l'image. Ce qui fait que même si l'image uploadée n'a pas le même ratio (16/9) que les 1920x1080, elle sera croppée pour faire la miniature.
La mention à `thumbnail_16_9_large` était ensuite utilisée comme paramètre pour la fonction permettant de renvoyer le code HTML …

Optimize image size for display (srcset)

---

wp-theme-2018/shortcodes/epfl_people/utils.php

Suite à la modification faite en urgence tout récemment sur People, toutes les URL d'images devenaient incorrectes... car pas de redirections faites depuis ancien nom vers nouveau... donc "404"...
Ajout du ".jpg" à la fin de l'URL, afin que ça corresponde à la nouvelle manière de faire.
Une manère de faire plus endurante face aux changements du côté de People serait d'utiliser un WebService qui retourne l'URL de l'image d'une personne donnée... mais ça impliquerait autant d'appels à ce WebService qu'il n'y aurait de personnes dont on aurait besoin de la photo... donc pas optimum du tout.

Fix people image URL

---

wp-theme-2018/shortcodes/epfl_news/utils.php

L'API REST de actu.epfl.ch va bientôt servir des images aux dimensions 1440x810.
Modification du shortcode en conséquence

Shortcode news : visual_url dimension change

---

wp-theme-2018/shortcodes/epfl_news/utils.php

Mettre à jour le lien "Toutes les actualités" afin de permettre de conserver la langue de navigation de l'utilisateur.
En effet, une modification a été fait dans l'outil actualités. 
**Exemple:** https://actu.epfl.ch/search/fr/enac
Sert une page avec toutes les news du canal enac et settant la langue de l'utilisateur à fr

update all news links

---

wp-theme-2018/shortcodes/epfl_labs_search/controller.php
wp-theme-2018/shortcodes/epfl_labs_search/javascript.php

Tous les sites chargent les CSS et le JS du plugin epfl_labs_search, ce qui, avouons-le, n'est pas la définition d'optimal. Cette PR fait en sorte que seule la page où le shortcode epfl_labs_search est appellé charge ces CSS et JS

Fix epfl_labs_search loading js an css globally

---

wp-theme-2018/shortcodes/epfl_memento/view.php

Pour le shortcode memento listing sans mise en valeur du 1er event, la largeur de div étant trop petite (comme il y avait le First event hightlighté).

Fix css bug for memento listing without highlight element

---

wp-theme-2018/shortcodes/epfl_news/utils.php
wp-theme-2018/shortcodes/epfl_news/view.php

Cette PR a pour but d'intégrer dans le shortcode epfl-news les vidéos courtes provenenant de vimeo (avec un compte payant) permettant de les configurer comme souhaité.
- pas de son
- se lance automatiquement
- boucle sur elle même
- pas de boutons affichés

integration of vimeo short video

---

wp-theme-2018/functions.php

Suite au wagon de changes du 06.06.2019 dans lequel on a fait en sorte que le slug de la langue soit présent dans l'URL pour toutes les langues, le lien présent sur le logo EPFL en haut à gauche était faux pour la langue FR (il renvoyait à la racine).
- Correction du lien pour la homepage en FR
- Suppression d'une fonction utilisée nulle part (j'ai check thème et plugins) car pas d'intérêt à garder du code mort.

Add 'fr/' for French page, remove unused and confusing func

---

wp-theme-2018/footer.php

J'ai déplacé l'appel de la fonction wp_footer, ça doit toujours être le dernier élément avant la balise </body>. Comme elle se trouvait avant la fermeture du div #page, l'adminbar était placé à l'intérieur de ce div, ce qui causait le bug d'affichage.

Correction du bug d'affichage de l'adminbar

---

wp-theme-2018/functions.php

Remove the jquery depencies from video shortcode, so we don't generate conflicts when we have a gallery on the same page.
Forcing jQuery 3.x on video may have some side effects in the future. At the moment, it works as intended, so we will see if this need a better fix.

Fix video including a old jQuery version

---

wp-theme-2018/shortcodes/epfl_people/utils.php
wp-theme-2018/shortcodes/epfl_people/view.php

Uniformisation des numéros de téléphone venant de People. Il y en a certains qui sont au format "école court" : 31234 et d'autre, qui ne sont pas dans l'école et ceux-ci sont donc 0221234567 (ex pour Genève)
**AVANT** (cf problème remonté dans INC0297001)
- les formats courts étaient appondu à un préfixe donné: `+41 21 69 ` (Ex: `+41 21 69 31234`)
- les formats longs étaient aussi appondu au même préfixe, ex: `+41 21 69 0221234567`
**MAINTENANT** (dans cette PR)
- Uniformisation pour coller à la manière dont les nos de téléphone sont affichés normalement dans les annuaires et sur le net.
- Les formats courts deviennent : `+41 21 693 12 34`
- Les formats longs deviennent: `+41 22 123 45 67`

People: Uniformize phones number

---

wp-theme-2018/functions.php

This makes WordPress re-rootable, which is useful for test environments.

Add `epfl_home_url` option to change home URL in header and breadcrumb

---

wp-theme-2018/menus/blog-posts.php
wp-theme-2018/menus/utils.php
wp-theme-2018/sidebar.php

Cette PR vise à ce que les pages de détail d'un post et les pages de listing des posts se retrouvent correctement dans le menu, lorsque le site n'a pas configuré son menu correctement pour ces éléments de blogs.
Actuellement, on peut remarquer le problème ici :
https://www.epfl.ch/labs/alice/category/research/
Dans le breadcrump (et les menus), on voit 
"Laboratoires > Articles", avec cette PR on aura on "Laboratoires > ALICE > Articles"

Fix not using selected homepage as parent page

---

README.md
wp-theme-light/footer_fr.php

Following the rename of the epfl-idevelop GitHub organization to epfl-si today, we want to update all pointers (despite the old addresses still working for now).

[janitor] github.com/epfl-idevelop → github.com/epfl-si #25 

---

wp-theme-2018/footer_en.php
wp-theme-2018/footer_fr.php

Reverting epfl-si/wp-theme-2018#257 as the "back to top" button is taking too much place.

Revert "Add "back to top" button markup to the WP theme"

---

wp-theme-2018/inc/media-gallery.php

Linked with https://github.com/epfl-si/wp-gutenberg-epfl/pull/188

Set gallery drawer for gutenberg compatiblities; drop shortcode gallery support

---

wp-theme-2018/editor-styles.css
wp-theme-2018/functions.php

Strange enough, the old way to load the css was not working : 
add_theme_support( 'editor-style' ); should be add_theme_support( 'editor-styles' );
So some cleanup is welcome I guess, seeing this old content as an artefact of the old theme.

Hide password visibility settings in editor and Clean up unused editor-styles.css

---

wp-theme-2018/inc/media-gallery.php

In the gutenberg editor views, you can set different style to caption, like bold and italic. This PR allow the style in the final render of the gallery.
For INC0362296

Fix gallery not using the captions'style

---

wp-theme-2018/template-parts/breadcrumb.php

The query string is a part of the `$_SERVER['REQUEST_URI']` so we have to delete it at the beginning of the construction of the current page url.

[Fix] remove query string from $_SERVER['REQUEST_URI']

---

wp-theme-2018/template-parts/breadcrumb.php

All languages different not in ('en', 'fr', 'de') arenot taken by the breadcrum and the english language is given as default: 
`$current_lang = get_current_language();`
where:
`function get_current_language ($default_lang='en') {
$allowed_langs = array('en', 'fr', 'de');
$language = $default_lang;
/* If Polylang installed */
if(function_exists('pll_current_language'))
{
$current_lang = pll_current_language('slug');
// Check if current lang is supported. If not, use default lang
$language = (in_array($current_lang, $allowed_langs)) ? $current_lang : $default_lang;
}
return $language;
}`
So the theme for all other languages doens't show the breadcrumb.
A possible solution (it works locally) could be to get directly the current language from polylang but the following commit was made to …

[fix] get current language from polylang directly

---

wp-theme-2018/sidebar.php

Instead of call a wp web-hook defined into EPFL-Menu plugin, we now call the menu-api microservice as we already do into the breadcrumb

[feature](WPN-249) Call Menu-API microservice to fill out the navigation menu in the left sidebar

---

wp-theme-2018/menu_microservice.inc
wp-theme-2018/sidebar.php
wp-theme-2018/template-parts/breadcrumb.php

We don't want to burden the menu API microservice (and specifically, lengthen the pod's startup time) for our use cases which don't actually depend on menu stitching.

[fix] Limit the DNS domains for which we consume the menu-api microservice
